export const DEFAULT_ITEMS = [
  {id: 0, text: "Dinner with Jess", completed: false, category: "personal"},
  {id: 1, text: "Pay Rent", completed: true, category: "personal"},
  {id: 2, text: "Learn monads", completed: false, category: "work"},
]

export const DEFAULT_ITEMS_longList = [
  {id: 0, text: "Dinner with Jess", completed: false, category: "personal"},
  {id: 1, text: "Pay Rent", completed: true, category: "personal"},
  {id: 2, text: "Learn monads", completed: false, category: "work"},
  {id: 3, text: "Learn monads", completed: false, category: "work"},
  {id: 4, text: "Learn monads", completed: false, category: "work"},
  {id: 5, text: "Learn monads", completed: false, category: "work"},
  {id: 6, text: "Learn monads", completed: false, category: "work"},
  {id: 7, text: "Learn monads", completed: false, category: "work"},
  {id: 8, text: "Learn monads", completed: false, category: "work"},
  {id: 9, text: "Learn monads", completed: false, category: "work"},
  {id: 10, text: "Learn monads", completed: false, category: "work"},
  {id: 11, text: "Learn monads", completed: false, category: "work"},
  {id: 12, text: "Learn monads", completed: false, category: "work"},
  {id: 13, text: "Learn monads", completed: false, category: "work"},
  {id: 14, text: "Learn monads", completed: false, category: "work"},
  {id: 15, text: "Learn monads", completed: false, category: "work"},
  {id: 16, text: "Learn monads", completed: false, category: "work"},
  {id: 17, text: "Learn monads", completed: false, category: "work"},
  {id: 18, text: "Learn monads", completed: false, category: "work"},
  {id: 19, text: "Learn monads", completed: false, category: "work"},
  {id: 20, text: "Learn monads", completed: false, category: "work"},
  {id: 21, text: "Learn monads", completed: false, category: "work"},
  {id: 22, text: "Learn monads", completed: false, category: "work"},
  {id: 23, text: "Learn monads", completed: false, category: "work"},
  {id: 24, text: "Learn monads", completed: false, category: "work"},
  {id: 25, text: "Learn monads", completed: false, category: "work"},
  {id: 26, text: "Learn monads", completed: false, category: "work"},
  {id: 27, text: "Learn monads", completed: false, category: "work"},
  {id: 28, text: "Learn monads", completed: false, category: "work"},
  {id: 29, text: "Learn monads", completed: false, category: "work"},
  {id: 30, text: "Learn monads", completed: false, category: "work"},
]